/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brazorobotico;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;

/**
 *
 * @author angel
 */
public class window extends javax.swing.JFrame {

    /**
     * Creates new form window
     */
    
    boolean conectado;
    
    //enviarComandos classSend = new enviarComandos();
    
    PanamaHitek_Arduino ino = new PanamaHitek_Arduino();
    public window() {
        initComponents();
        CardLayout card = (CardLayout) mainPane.getLayout();
        card.show(mainPane, "inicioPane");
        conectado = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        menuButton_console = new javax.swing.JButton();
        menuButton_inicio = new javax.swing.JButton();
        menuButton_control = new javax.swing.JButton();
        menuButton_upload = new javax.swing.JButton();
        buttonMenu_exit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainPane = new javax.swing.JPanel();
        inicioPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        controlPane = new javax.swing.JPanel();
        slider_rotor = new javax.swing.JSlider();
        textField_rotor = new javax.swing.JTextField();
        slider_brazo = new javax.swing.JSlider();
        textField_brazo = new javax.swing.JTextField();
        comandosPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        comandosPane_textArea_comandos = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comandosPane_button_realizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        comandosPane_combPuertos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        consolaPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        consolaPane_button_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        menuButton_console.setBackground(new java.awt.Color(0, 0, 255));
        menuButton_console.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Console-50.png"))); // NOI18N
        menuButton_console.setBorder(null);
        menuButton_console.setBorderPainted(false);
        menuButton_console.setContentAreaFilled(false);
        menuButton_console.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton_consoleActionPerformed(evt);
            }
        });

        menuButton_inicio.setBackground(new java.awt.Color(0, 0, 255));
        menuButton_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Xbox Menu-50.png"))); // NOI18N
        menuButton_inicio.setBorder(null);
        menuButton_inicio.setBorderPainted(false);
        menuButton_inicio.setContentAreaFilled(false);
        menuButton_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton_inicioActionPerformed(evt);
            }
        });

        menuButton_control.setBackground(new java.awt.Color(0, 0, 255));
        menuButton_control.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Control Panel-50.png"))); // NOI18N
        menuButton_control.setBorder(null);
        menuButton_control.setBorderPainted(false);
        menuButton_control.setContentAreaFilled(false);
        menuButton_control.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton_controlActionPerformed(evt);
            }
        });

        menuButton_upload.setBackground(new java.awt.Color(0, 0, 255));
        menuButton_upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Upload-50.png"))); // NOI18N
        menuButton_upload.setBorder(null);
        menuButton_upload.setBorderPainted(false);
        menuButton_upload.setContentAreaFilled(false);
        menuButton_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton_uploadActionPerformed(evt);
            }
        });

        buttonMenu_exit.setBackground(new java.awt.Color(0, 0, 255));
        buttonMenu_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Multiply-50.png"))); // NOI18N
        buttonMenu_exit.setBorder(null);
        buttonMenu_exit.setBorderPainted(false);
        buttonMenu_exit.setContentAreaFilled(false);
        buttonMenu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenu_exitActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuButton_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(menuButton_control, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(menuButton_console, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonMenu_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(menuButton_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuButton_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuButton_control, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuButton_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuButton_console, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(buttonMenu_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 540));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Brazo robotico v1.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 610, 70));

        mainPane.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 0, 48)); // NOI18N
        jLabel2.setText("v1");

        javax.swing.GroupLayout inicioPaneLayout = new javax.swing.GroupLayout(inicioPane);
        inicioPane.setLayout(inicioPaneLayout);
        inicioPaneLayout.setHorizontalGroup(
            inicioPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioPaneLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel2)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        inicioPaneLayout.setVerticalGroup(
            inicioPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioPaneLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel2)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        mainPane.add(inicioPane, "inicioPane");

        controlPane.setName("Control"); // NOI18N

        slider_rotor.setMaximum(180);
        slider_rotor.setValue(0);
        slider_rotor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_rotorStateChanged(evt);
            }
        });

        textField_rotor.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        textField_rotor.setText("0");
        textField_rotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_rotorActionPerformed(evt);
            }
        });

        slider_brazo.setMaximum(180);
        slider_brazo.setOrientation(javax.swing.JSlider.VERTICAL);
        slider_brazo.setValue(0);
        slider_brazo.setPreferredSize(new java.awt.Dimension(26, 200));
        slider_brazo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_brazoStateChanged(evt);
            }
        });

        textField_brazo.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        textField_brazo.setText("0");
        textField_brazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_brazoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPaneLayout = new javax.swing.GroupLayout(controlPane);
        controlPane.setLayout(controlPaneLayout);
        controlPaneLayout.setHorizontalGroup(
            controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(slider_brazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(textField_brazo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(controlPaneLayout.createSequentialGroup()
                .addGroup(controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPaneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(slider_rotor, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controlPaneLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(textField_rotor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        controlPaneLayout.setVerticalGroup(
            controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPaneLayout.createSequentialGroup()
                .addGroup(controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slider_brazo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(controlPaneLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(textField_brazo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider_rotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_rotor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPane.add(controlPane, "controlPane");

        comandosPane_textArea_comandos.setColumns(20);
        comandosPane_textArea_comandos.setRows(5);
        comandosPane_textArea_comandos.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane2.setViewportView(comandosPane_textArea_comandos);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Comandos:");

        jLabel6.setText("ROTOR angulo;");

        jLabel7.setText("BRAZO angulo;");

        comandosPane_button_realizar.setText("Realizar");
        comandosPane_button_realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comandosPane_button_realizarActionPerformed(evt);
            }
        });

        jButton2.setText("Repetir infinitamente");

        jButton3.setText("Repetir cantidad");

        jButton4.setText("Limpiar");

        jButton5.setText("Subir txt");

        jButton1.setText("Conectar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comandosPaneLayout = new javax.swing.GroupLayout(comandosPane);
        comandosPane.setLayout(comandosPaneLayout);
        comandosPaneLayout.setHorizontalGroup(
            comandosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comandosPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comandosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comandosPaneLayout.createSequentialGroup()
                        .addComponent(comandosPane_button_realizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(comandosPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(comandosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(comandosPaneLayout.createSequentialGroup()
                        .addComponent(comandosPane_combPuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        comandosPaneLayout.setVerticalGroup(
            comandosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comandosPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comandosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comandosPane_combPuertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(comandosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comandosPane_button_realizar)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comandosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(comandosPaneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(42, 42, 42)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap())
        );

        mainPane.add(comandosPane, "comandosPane");

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(51, 255, 51));

        consola.setEditable(false);
        consola.setBackground(new java.awt.Color(0, 0, 0));
        consola.setColumns(20);
        consola.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        consola.setForeground(new java.awt.Color(0, 204, 0));
        consola.setRows(5);
        consola.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(consola);

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 36)); // NOI18N
        jLabel5.setText("Consola");

        consolaPane_button_limpiar.setText("Limpiar");
        consolaPane_button_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consolaPane_button_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consolaPaneLayout = new javax.swing.GroupLayout(consolaPane);
        consolaPane.setLayout(consolaPaneLayout);
        consolaPaneLayout.setHorizontalGroup(
            consolaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consolaPaneLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(consolaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consolaPane_button_limpiar)
                    .addGroup(consolaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        consolaPaneLayout.setVerticalGroup(
            consolaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(consolaPane_button_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        mainPane.add(consolaPane, "consolaPane");

        getContentPane().add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 610, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButton_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton_inicioActionPerformed
        cambiarCapa("inicioPane");
    }//GEN-LAST:event_menuButton_inicioActionPerformed

    private void buttonMenu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenu_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonMenu_exitActionPerformed

    private void menuButton_controlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton_controlActionPerformed
        cambiarCapa("controlPane");
    }//GEN-LAST:event_menuButton_controlActionPerformed

    private void slider_rotorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_rotorStateChanged
        textField_rotor.setText(Integer.toString(slider_rotor.getValue()));
        try {
            ino.sendData("ROTOR " + Integer.toString(slider_rotor.getValue()) + "\n");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_slider_rotorStateChanged

    private void textField_rotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_rotorActionPerformed
        int angulo = 0;
        try{
            angulo = Integer.parseInt(textField_rotor.getText());
            if(angulo<=180 && angulo>=0)
                slider_rotor.setValue(Integer.parseInt(textField_rotor.getText()));
            else{
                JOptionPane.showMessageDialog(null,"Solo se pueden enviar valores enteros entre 0 y 180");
            if(angulo>180){
                slider_rotor.setValue(180);
                textField_rotor.setText("180");
            }
            if(angulo<180){
                slider_rotor.setValue(0);
                textField_rotor.setText("0");
            }}
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Solo se pueden enviar valores enteros entre 0 y 180");
            slider_rotor.setValue(0);
            textField_rotor.setText("0");
        }
    }//GEN-LAST:event_textField_rotorActionPerformed

    private void menuButton_consoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton_consoleActionPerformed
        cambiarCapa("consolaPane");
    }//GEN-LAST:event_menuButton_consoleActionPerformed

    private void textField_brazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_brazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_brazoActionPerformed

    private void slider_brazoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_brazoStateChanged
        textField_brazo.setText(Integer.toString(slider_brazo.getValue()));
        try {
            ino.sendData("BRAZO " + Integer.toString(slider_brazo.getValue()) + "\n");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_slider_brazoStateChanged

    private void consolaPane_button_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consolaPane_button_limpiarActionPerformed
        consola.setText(null);
    }//GEN-LAST:event_consolaPane_button_limpiarActionPerformed

    private void comandosPane_button_realizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comandosPane_button_realizarActionPerformed
        String[] lineas = comandosPane_textArea_comandos.getText().split(";");
        //enviarComandos sendPack = new enviarComandos();
    }//GEN-LAST:event_comandosPane_button_realizarActionPerformed

    private void menuButton_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton_uploadActionPerformed
        cambiarCapa("comandosPane");
        enviarComandos puertos =new enviarComandos();
        
        for(int i=0; i<ino.getSerialPorts().size(); i++){
            comandosPane_combPuertos.addItem(puertos.getPorts().get(i));
        }
    }//GEN-LAST:event_menuButton_uploadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enviarComandos connect = new enviarComandos();
        connect.conectar(comandosPane_combPuertos.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    //manejador de capas con card layout
    void cambiarCapa(String nombreCapa){
        CardLayout card = (CardLayout) mainPane.getLayout();
        card.show(mainPane, nombreCapa);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new window().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMenu_exit;
    private javax.swing.JPanel comandosPane;
    private javax.swing.JButton comandosPane_button_realizar;
    private javax.swing.JComboBox<String> comandosPane_combPuertos;
    private javax.swing.JTextArea comandosPane_textArea_comandos;
    public javax.swing.JTextArea consola;
    private javax.swing.JPanel consolaPane;
    private javax.swing.JButton consolaPane_button_limpiar;
    private javax.swing.JPanel controlPane;
    private javax.swing.JPanel inicioPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPane;
    private javax.swing.JButton menuButton_console;
    private javax.swing.JButton menuButton_control;
    private javax.swing.JButton menuButton_inicio;
    private javax.swing.JButton menuButton_upload;
    private javax.swing.JSlider slider_brazo;
    private javax.swing.JSlider slider_rotor;
    private javax.swing.JTextField textField_brazo;
    private javax.swing.JTextField textField_rotor;
    // End of variables declaration//GEN-END:variables
}
